spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/GardenDB?useSSL=false&character
    username: root
    password:
  session:
    store-type: jdbc
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl-auto: create
    show_sql: true